package domain

import (
	"fmt"
	"path"
	"sort"
	"strings"
	"sync"
	"time"
)

// FileEntry represents a file in the virtual filesystem.
type FileEntry struct {
	Content     string
	Permissions string
	Owner       string
	Group       string
	Size        int
	Mtime       string
}

func NewFileEntry(content string) *FileEntry {
	return &FileEntry{
		Content:     content,
		Permissions: "-rw-r--r--",
		Owner:       "root",
		Group:       "root",
		Size:        len(content),
		Mtime:       time.Now().UTC().Format("2006-01-02 15:04"),
	}
}

func NewDirEntry(owner string) *FileEntry {
	if owner == "" {
		owner = "root"
	}
	return &FileEntry{
		Content:     "",
		Permissions: "drwxr-xr-x",
		Owner:       owner,
		Group:       owner,
		Size:        4096,
		Mtime:       time.Now().UTC().Format("2006-01-02 15:04"),
	}
}

// CachedRule stores an LLM-generated response for consistent replay.
type CachedRule struct {
	Key       string
	Command   string // ls, cat, find, grep, etc.
	Path      string // target path
	Flags     string // command flags
	Output    string // cached LLM output
	CreatedAt time.Time
	HitCount  int
}

// DynamicRuleCache stores LLM-generated responses so repeated commands
// return identical output. When the attacker modifies the filesystem,
// affected entries are invalidated and re-generated on next access.
type DynamicRuleCache struct {
	rules map[string]*CachedRule
	mu    sync.RWMutex
}

func NewDynamicRuleCache() *DynamicRuleCache {
	return &DynamicRuleCache{rules: make(map[string]*CachedRule)}
}

// CacheKey builds a normalized cache key from command components.
func CacheKey(command, flags, targetPath string) string {
	flags = strings.TrimSpace(flags)
	if flags != "" {
		return command + ":" + flags + ":" + targetPath
	}
	return command + ":" + targetPath
}

// Lookup returns a cached rule or nil.
func (c *DynamicRuleCache) Lookup(key string) *CachedRule {
	c.mu.RLock()
	defer c.mu.RUnlock()
	r, ok := c.rules[key]
	if !ok {
		return nil
	}
	r.HitCount++
	return r
}

// Store saves an LLM response in the cache.
func (c *DynamicRuleCache) Store(key, command, targetPath, flags, output string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.rules[key] = &CachedRule{
		Key:       key,
		Command:   command,
		Path:      targetPath,
		Flags:     flags,
		Output:    output,
		CreatedAt: time.Now(),
	}
}

// InvalidateDir removes all cached rules whose Path equals or is a
// child of dir. This is called when the attacker writes to the filesystem.
func (c *DynamicRuleCache) InvalidateDir(dir string) {
	dir = path.Clean(dir)
	c.mu.Lock()
	defer c.mu.Unlock()
	for key, r := range c.rules {
		rp := path.Clean(r.Path)
		if rp == dir || strings.HasPrefix(rp, dir+"/") {
			delete(c.rules, key)
		}
	}
}

// InvalidateFile removes cached rules for a specific file path (cat cache).
func (c *DynamicRuleCache) InvalidateFile(filepath string) {
	filepath = path.Clean(filepath)
	c.mu.Lock()
	defer c.mu.Unlock()
	for key, r := range c.rules {
		if r.Command == "cat" && path.Clean(r.Path) == filepath {
			delete(c.rules, key)
		}
	}
}

// WorldState is the virtual filesystem for a session.
type WorldState struct {
	files map[string]*FileEntry
	cache *DynamicRuleCache
}

// NewWorldState creates a world state with default files.
func NewWorldState() *WorldState {
	w := &WorldState{
		files: make(map[string]*FileEntry),
		cache: NewDynamicRuleCache(),
	}
	w.initDefaults()
	return w
}

// NewWorldStateForHost creates a world state for a remote host.
// Only critical attack-chain clue files are pre-seeded; all other content
// is generated by the LLM fallback on demand.
func NewWorldStateForHost(hostname string) *WorldState {
	w := &WorldState{
		files: make(map[string]*FileEntry),
		cache: NewDynamicRuleCache(),
	}
	w.initHostStructure(hostname)
	w.initHostClueFiles(hostname)
	return w
}

// initHostStructure sets up a minimal directory tree so that ls /
// returns something sensible before LLM fallback kicks in.
func (w *WorldState) initHostStructure(hostname string) {
	dirs := []string{
		"/",
		"/bin", "/boot", "/dev", "/etc", "/home", "/lib", "/lib64", "/media",
		"/mnt", "/opt", "/proc", "/root", "/run", "/sbin", "/srv", "/sys",
		"/tmp", "/usr", "/var",
		"/usr/bin", "/usr/lib", "/usr/local", "/usr/sbin", "/usr/share",
		"/var/log", "/var/tmp", "/var/run", "/var/lib", "/var/cache",
		"/root/.ssh", "/home",
	}
	switch hostname {
	case "jump01":
		dirs = append(dirs, "/home/ansible", "/home/ansible/.ssh",
			"/opt/tools", "/etc/ansible", "/etc/ansible/playbooks")
	case "dc01":
		dirs = append(dirs, "/home/administrator", "/home/administrator/scripts",
			"/Users", "/Users/administrator", "/Users/administrator/Desktop",
			"/opt/ad-tools", "/opt/ad-tools/output")
	}
	for _, d := range dirs {
		owner := "root"
		if strings.Contains(d, "ansible") {
			owner = "ansible"
		} else if strings.Contains(d, "administrator") {
			owner = "administrator"
		}
		w.files[d] = NewDirEntry(owner)
	}
	// Set hostname
	w.files["/etc/hostname"] = NewFileEntry(hostname + "\n")

	// Set host-specific system files
	switch hostname {
	case "jump01":
		w.files["/etc/hosts"] = NewFileEntry(`127.0.0.1       localhost
192.168.56.1    gateway gateway.corp.local
192.168.56.10   jump01 jump01.corp.local
192.168.56.23   staging-web-01 staging-web-01.corp.local
192.168.56.50   dc01 dc01.corp.local
192.168.56.60   fin-db01 fin-db01.corp.local
192.168.56.80   gitlab-internal gitlab-internal.corp.local
`)
		w.files["/etc/resolv.conf"] = NewFileEntry(`nameserver 192.168.56.50
search corp.local
options ndots:5
`)
		w.files["/etc/os-release"] = NewFileEntry(`PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
`)
		w.files["/root/.bashrc"] = NewFileEntry(`# ~/.bashrc: executed by bash(1) for non-login shells.
export PATH=$PATH:/usr/local/bin:/opt/tools
export HISTSIZE=1000
export HISTFILESIZE=2000
alias ll='ls -la'
alias la='ls -A'
`)
		w.files["/root/.bash_history"] = NewFileEntry(`ssh-keyscan -H 192.168.56.23 >> ~/.ssh/known_hosts
ssh ansible@staging-web-01
sudo su -
cd /opt
git clone http://gitlab-internal/devops/deploy-scripts.git
cd deploy-scripts
cat .git/config
export GITLAB_TOKEN='glpat-Xy7kQw3r9mNpLz1v'
./deploy.sh --env=prod
curl -H "PRIVATE-TOKEN: $GITLAB_TOKEN" http://gitlab-internal/api/v4/projects
kubectl config set-cluster cloud-cluster --server=https://10.20.0.10:6443
kubectl config set-credentials cloud-admin --token=eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9...
java -jar jenkins-cli.jar -s http://jenkins-internal:8080/ auth
cat /etc/ansible/facts.d/secrets.fact
ansible-vault view /etc/ansible/vault/vault.yml --ask-vault-pass
nmap -sV 10.10.20.0/24
ssh root@10.10.20.10
ssh administrator@192.168.56.50
`)
		w.files["/home/ansible/.bashrc"] = NewFileEntry(`export PATH=$PATH:/usr/local/bin:/opt/tools
export ANSIBLE_HOST_KEY_CHECKING=False
`)
		w.files["/home/ansible/.bashrc"].Owner = "ansible"

	case "dc01":
		w.files["/etc/hosts"] = NewFileEntry(`127.0.0.1       localhost
192.168.56.1    gateway gateway.corp.local
192.168.56.10   jump01 jump01.corp.local
192.168.56.50   dc01 dc01.corp.local
192.168.56.60   fin-db01 fin-db01.corp.local
172.16.10.5     dmz-web-01 dmz-web-01.dmz.local
172.16.10.10    dmz-mail-01 dmz-mail-01.dmz.local
`)
		w.files["/etc/resolv.conf"] = NewFileEntry(`nameserver 192.168.56.50
search corp.local
options ndots:5
`)
		w.files["/etc/os-release"] = NewFileEntry(`NAME="Windows Server 2019"
VERSION="10.0.17763"
ID=windows
`)
		w.files["/root/.bash_history"] = NewFileEntry(`whoami
ipconfig /all
net user /domain
net group "Domain Admins" /domain
nltest /dclist:corp.local
klist
mimikatz
lsadump::dcsync /domain:corp.local /user:administrator
export KRB5CCNAME=/tmp/administrator.ccache
evil-winrm -i dc01 -u administrator -H aad3b435b51404eeaad3b435b51404ee
ssh admin@172.16.10.5
cat /Users/administrator/Desktop/credentials.txt
`)
	}
}

// initHostClueFiles pre-seeds ONLY the files that carry attack-chain clues.
// Everything else is left to the LLM fallback.
func (w *WorldState) initHostClueFiles(hostname string) {
	switch hostname {
	case "jump01":
		w.files["/opt/tools/scan_results.txt"] = NewFileEntry(`# nmap scan results - 2024-01-14
# Finance subnet discovered via pivot from staging-web-01
Nmap scan report for 10.10.20.0/24
Host: 10.10.20.10 ()	Status: Up
  PORT     STATE SERVICE
  22/tcp   open  ssh
  8080/tcp open  http-proxy

Host: 10.10.20.20 ()	Status: Up
  PORT     STATE SERVICE
  22/tcp   open  ssh
  3306/tcp open  mysql
  6379/tcp open  redis

Host: 10.10.20.1 ()	Status: Up
  PORT     STATE SERVICE
  22/tcp   open  ssh
`)
		w.files["/opt/tools/scan_results.txt"].Owner = "ansible"

		w.files["/etc/ansible/hosts"] = NewFileEntry(`[staging]
staging-web-01 ansible_host=192.168.56.23

[jumpbox]
jump01 ansible_host=192.168.56.10

[finance]
fin-app-01 ansible_host=10.10.20.10
fin-db-master ansible_host=10.10.20.20

[domain]
dc01 ansible_host=192.168.56.50
`)

	case "dc01":
		w.files["/Users/administrator/Desktop/credentials.txt"] = NewFileEntry(`# DMZ Server Credentials - PRODUCTION
# Last updated: 2024-01-10
# DO NOT SHARE

# DC01 SSH
dc01 (192.168.56.50)
  user: administrator
  pass: P@ssw0rd!

# DMZ Servers
dmz-web-01 (172.16.10.5)
  user: admin
  pass: Dmz@Web2024!
  ssh-key: /Users/administrator/.ssh/dmz_key

dmz-mail-01 (172.16.10.10)
  user: postmaster
  pass: Mail@Dmz2024!
  note: IMAP requires VPN, SMTP open internally

# Finance DB (direct access from DC)
fin-db-master (10.10.20.20)
  user: sa
  pass: Fin@Master2024!
  port: 3306
`)
		w.files["/Users/administrator/Desktop/credentials.txt"].Owner = "administrator"
		w.files["/Users/administrator/Desktop/credentials.txt"].Permissions = "-rw-------"

		w.files["/opt/ad-tools/kerberoast_output.txt"] = NewFileEntry(`# Impacket Kerberoast - 2024-01-12
# Service accounts with SPNs

SPN: MSSQLSvc/fin-db-master.corp.local:1433
  sAMAccountName: svc_mssql
  Password: Sql@Service2024!
  LastLogon: 2024-01-10

SPN: HTTP/dmz-web-01.corp.local
  sAMAccountName: svc_web
  Password: Web@Service2024!
  LastLogon: 2024-01-08

SPN: SMTP/dmz-mail-01.corp.local
  sAMAccountName: svc_mail
  Password: Mail@Service2024!
  LastLogon: 2024-01-11
`)
	}
}

// Cache returns the dynamic rule cache for this world state.
func (w *WorldState) Cache() *DynamicRuleCache {
	return w.cache
}

func (w *WorldState) initDefaults() {
	// === Directory structure ===
	dirs := []string{
		"/",
		"/bin", "/boot", "/dev", "/etc", "/home", "/lib", "/lib64", "/media", "/mnt", "/opt", "/proc", "/root", "/run", "/sbin", "/srv", "/sys", "/tmp", "/usr", "/var",
		"/etc/default", "/etc/init.d", "/etc/network", "/etc/nginx", "/etc/mysql", "/etc/systemd", "/etc/systemd/system", "/etc/apt",
		"/home/www-data", "/home/ansible", "/home/deploy",
		"/opt/webapp", "/opt/webapp/logs", "/opt/webapp/scripts", "/opt/webapp/static",
		"/proc/net", "/proc/sys",
		"/root/.ssh", "/root/.cache",
		"/tmp", "/var/backups", "/var/cache", "/var/lib", "/var/log", "/var/mail", "/var/opt", "/var/run", "/var/spool", "/var/tmp",
		"/var/lib/mysql", "/var/lib/nginx", "/var/log/nginx", "/var/log/mysql",
		"/var/www", "/var/www/html",
		"/usr/bin", "/usr/lib", "/usr/local", "/usr/sbin", "/usr/share",
		"/run/lock", "/run/sshd",
	}
	for _, d := range dirs {
		owner := "root"
		if strings.HasPrefix(d, "/home/www-data") {
			owner = "www-data"
		}
		w.files[d] = NewDirEntry(owner)
	}

	// === /opt/webapp - the web application ===
	w.files["/opt/webapp/.env"] = NewFileEntry(
		`# Database Configuration
DB_HOST=192.168.56.60
DB_PORT=3306
DB_NAME=fin_readonly_` + DeploySeed + `
DB_USER=web_ro
DB_PASSWORD=WebApp@2024!Ro

# Redis
REDIS_HOST=192.168.56.30
REDIS_PORT=6379
REDIS_PASSWORD=Redis@2024!` + DeploySeed + `

# App Secret
APP_SECRET_KEY=sk-` + DeploySeed + `-prod-a8f3e2b1c9d7
JWT_SECRET=jwt-` + DeploySeed + `-2024-xK9mN2pL

# GitLab Internal
GITLAB_URL=http://192.168.56.80
GITLAB_TOKEN=glpat-` + DeploySeed + `-deploy-token

# Jenkins CI
JENKINS_URL=http://192.168.56.45:8080
JENKINS_USER=deploy
JENKINS_TOKEN=jenkins-` + DeploySeed + `-build-token
`)
	w.files["/opt/webapp/.env"].Owner = "www-data"
	w.files["/opt/webapp/.env"].Group = "www-data"

	w.files["/opt/webapp/app.py"] = NewFileEntry(`#!/usr/bin/env python3
import os
from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/health')
def health():
    return jsonify(status='ok')

@app.route('/api/data')
def data():
    db_host = os.getenv('DB_HOST')
    return jsonify(source=db_host)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
`)
	w.files["/opt/webapp/app.py"].Owner = "www-data"
	w.files["/opt/webapp/app.py"].Permissions = "-rwxr-xr-x"

	w.files["/opt/webapp/config.yaml"] = NewFileEntry(`server:
  host: 0.0.0.0
  port: 5000
  workers: 4

database:
  host: 192.168.56.60
  port: 3306
  name: fin_readonly_` + DeploySeed + `
  user: web_ro
  password: WebApp@2024!Ro
  pool_size: 10

redis:
  host: 192.168.56.30
  port: 6379
  db: 0

logging:
  level: INFO
  file: /opt/webapp/logs/app.log
`)

	w.files["/opt/webapp/logs/app.log"] = NewFileEntry(`2024-01-15 08:12:33 [INFO] Application started on port 5000
2024-01-15 08:12:34 [INFO] Connected to MySQL at 192.168.56.60:3306
2024-01-15 08:12:34 [INFO] Redis connected at 192.168.56.30:6379
2024-01-15 08:15:01 [WARN] High memory usage detected: 78%
2024-01-15 08:20:45 [INFO] Health check passed
2024-01-15 08:25:12 [ERROR] Connection timeout to gitlab-internal (192.168.56.80)
2024-01-15 08:30:00 [INFO] Scheduled backup started
2024-01-15 08:35:22 [INFO] Backup completed: 2.3GB dumped to /backups/
2024-01-15 09:00:00 [INFO] Jenkins deploy webhook received from 192.168.56.45
2024-01-15 09:05:15 [INFO] Deploy triggered: version 2.4.1
2024-01-15 09:10:33 [INFO] Health check passed after deploy
`)
	w.files["/opt/webapp/logs/app.log"].Owner = "www-data"

	w.files["/opt/webapp/scripts/backup.sh"] = NewFileEntry(`#!/bin/bash
# Daily backup script
mysqldump -h 192.168.56.60 -u web_ro -p'WebApp@2024!Ro' fin_readonly_` + DeploySeed + ` > /backups/db_$(date +%Y%m%d).sql
tar czf /backups/app_$(date +%Y%m%d).tar.gz /opt/webapp/
`)
	w.files["/opt/webapp/scripts/backup.sh"].Permissions = "-rwxr-xr-x"
	w.files["/opt/webapp/scripts/backup.sh"].Owner = "www-data"

	w.files["/opt/webapp/scripts/deploy.sh"] = NewFileEntry(`#!/bin/bash
# Deploy script - triggered by Jenkins
cd /opt/webapp
git pull origin main
pip install -r requirements.txt
systemctl restart webapp
curl -s http://192.168.56.45:8080/job/webapp-deploy/lastBuild/consoleText
`)
	w.files["/opt/webapp/scripts/deploy.sh"].Permissions = "-rwxr-xr-x"
	w.files["/opt/webapp/scripts/deploy.sh"].Owner = "www-data"

	w.files["/opt/webapp/static/index.html"] = NewFileEntry(`<!DOCTYPE html>
<html><head><title>Staging Web App</title></head>
<body><h1>staging-web-01</h1><p>Internal staging environment</p></body>
</html>
`)

	// === /etc - system config ===
	w.files["/etc/hosts"] = NewFileEntry(`127.0.0.1       localhost
192.168.56.1    gateway gateway.corp.local
192.168.56.10   jump01 jump01.corp.local
192.168.56.23   staging-web-01 staging-web-01.corp.local
192.168.56.50   dc01 dc01.corp.local
192.168.56.60   fin-db01 fin-db01.corp.local
192.168.56.80   gitlab-internal gitlab-internal.corp.local
192.168.56.30   redis-cache redis-cache.corp.local
`)

	w.files["/etc/passwd"] = NewFileEntry(`root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-network:x:100:102::/run/systemd:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
mysql:x:27:27:MySQL Server:/var/lib/mysql:/bin/false
ansible:x:1001:1001:Ansible Service Account:/home/ansible:/bin/bash
jenkins:x:1002:1002:Jenkins CI:/var/lib/jenkins:/bin/bash
git:x:1003:1003:GitLab:/var/opt/gitlab:/bin/bash
postgres:x:104:110:PostgreSQL Admin:/var/lib/postgresql:/bin/bash
deploy:x:1005:1005:Deploy User:/home/deploy:/bin/bash
`)

	w.files["/etc/shadow"] = NewFileEntry(`root:$6$rounds=656000$randomsalt$hash:19737:0:99999:7:::
www-data:*:19737:0:99999:7:::
mysql:*:19737:0:99999:7:::
ansible:$6$rounds=656000$anothersalt$hash:19737:0:99999:7:::
`)

	w.files["/etc/hostname"] = NewFileEntry("staging-web-01\n")

	w.files["/etc/resolv.conf"] = NewFileEntry(`nameserver 192.168.56.50
search corp.local
options ndots:5
`)

	w.files["/etc/os-release"] = NewFileEntry(`PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
`)

	w.files["/etc/fstab"] = NewFileEntry(`# /etc/fstab: static file system information.
/dev/sda1   /          ext4   errors=remount-ro 0 1
/dev/sdb1   /opt       ext4   defaults          0 2
192.168.56.60:/exports/backups /backups nfs defaults 0 0
`)

	w.files["/etc/nginx/nginx.conf"] = NewFileEntry(`user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
}

http {
    upstream webapp {
        server 127.0.0.1:5000;
    }

    server {
        listen 80;
        server_name staging-web-01.corp.local;

        location / {
            proxy_pass http://webapp;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://webapp/health;
        }
    }
}
`)

	w.files["/etc/mysql/my.cnf"] = NewFileEntry(`[mysqld]
bind-address = 127.0.0.1
port = 3306
datadir = /var/lib/mysql
socket = /var/run/mysqld/mysqld.sock
log-error = /var/log/mysql/error.log

[client]
host = 192.168.56.60
port = 3306
user = web_ro
password = WebApp@2024!Ro
`)

	w.files["/etc/sudoers"] = NewFileEntry(`#
# This file MUST be edited with the 'visudo' command as root.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

root	ALL=(ALL:ALL) ALL
www-data ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart webapp, /usr/bin/systemctl status webapp
ansible	ALL=(ALL) NOPASSWD: ALL
deploy	ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/bin/kubectl

# See sudoers(5) for more information on "#include" directives:
#includedir /etc/sudoers.d
`)

	w.files["/etc/crontab"] = NewFileEntry(`# /etc/crontab: system-wide crontab
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user	command
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
0  3	* * *	root	/opt/webapp/scripts/backup.sh
`)

	w.files["/etc/systemd/system/webapp.service"] = NewFileEntry(`[Unit]
Description=Web Application Service
After=network.target mysql.service

[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=/opt/webapp
ExecStart=/usr/bin/python3 /opt/webapp/app.py
Restart=always
RestartSec=5
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
`)
	w.files["/etc/systemd/system/webapp.service"].Owner = "root"

	w.files["/etc/group"] = NewFileEntry(`root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
sudo:x:27:ansible,deploy
www-data:x:33:
mysql:x:27:
ansible:x:1001:
jenkins:x:1002:
git:x:1003:
docker:x:999:deploy,jenkins
postgres:x:104:
deploy:x:1005:
`)

	w.files["/etc/timezone"] = NewFileEntry("Asia/Shanghai\n")

	w.files["/etc/apt/sources.list"] = NewFileEntry(`deb http://archive.ubuntu.com/ubuntu jammy main restricted
deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted
deb http://archive.ubuntu.com/ubuntu jammy universe
deb http://archive.ubuntu.com/ubuntu jammy-updates universe
deb http://security.ubuntu.com/ubuntu jammy-security main restricted
deb http://security.ubuntu.com/ubuntu jammy-security universe
`)

	// === /root ===
	w.files["/root/.bashrc"] = NewFileEntry(`# ~/.bashrc: executed by bash(1) for non-login shells.
export PATH=$PATH:/usr/local/bin
export HISTSIZE=1000
export HISTFILESIZE=2000
alias ll='ls -la'
alias la='ls -A'
`)

	w.files["/root/.bash_history"] = NewFileEntry(`mysql -h 192.168.56.60 -u web_ro -p
cat /opt/webapp/.env
systemctl status webapp
docker ps
kubectl get pods
ssh ansible@192.168.56.10
curl http://192.168.56.80
grep -Ri token /opt/webapp
`)

	w.files["/root/.ssh/known_hosts"] = NewFileEntry(`192.168.56.10 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTY...
192.168.56.80 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTY...
`)

	w.files["/root/.ssh/id_rsa"] = NewFileEntry(`-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA0root_placeholder_key_for_honeypot_do_not_use_in_production
ZGV2c3RhZ2luZy13ZWItMDEAABQAAAAIAAABlwAAAAdzc2gtcnNhAAABBAFplaceholder
-----END OPENSSH PRIVATE KEY-----
`)
	w.files["/root/.ssh/id_rsa"].Permissions = "-rw-------"

	w.files["/root/.ssh/id_rsa.pub"] = NewFileEntry(`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0root_placeholder_key_for_honeypot root@staging-web-01
`)

	w.files["/root/.ssh/authorized_keys"] = NewFileEntry(`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0admin_key_placeholder admin@jump01
`)

	w.files["/root/.profile"] = NewFileEntry(`# ~/.profile: executed by the command interpreter for login shells.
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
`)

	w.files["/root/.vimrc"] = NewFileEntry(`set number
set tabstop=4
set shiftwidth=4
set expandtab
syntax on
`)

	w.files["/root/.gitconfig"] = NewFileEntry(`[user]
	name = ops-admin
	email = ops@corp.local
[core]
	editor = vim
`)

	// === /home ===
	w.files["/home/www-data/.bashrc"] = NewFileEntry(`export PATH=$PATH:/usr/local/bin
export APP_ENV=staging
`)
	w.files["/home/www-data/.bashrc"].Owner = "www-data"

	w.files["/home/ansible/.ssh/id_rsa"] = NewFileEntry(`-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA0placeholder_key_for_honeypot_do_not_use
-----END OPENSSH PRIVATE KEY-----
`)
	w.files["/home/ansible/.ssh/id_rsa"].Owner = "ansible"
	w.files["/home/ansible/.ssh/id_rsa"].Permissions = "-rw-------"

	w.files["/home/ansible/.ssh/config"] = NewFileEntry(`Host jump01
    HostName 192.168.56.10
    User ansible
    IdentityFile ~/.ssh/id_rsa
    # Password: ansible123

Host fin-db01
    HostName 192.168.56.60
    User root
    IdentityFile ~/.ssh/id_rsa

Host gitlab-internal
    HostName 192.168.56.80
    User git
    IdentityFile ~/.ssh/id_rsa
`)
	w.files["/home/ansible/.ssh/config"].Owner = "ansible"

	w.files["/home/ansible/playbooks/deploy.yml"] = NewFileEntry(`---
- name: Deploy webapp
  hosts: staging-web-01
  become: yes
  tasks:
    - name: Pull latest code
      git:
        repo: http://192.168.56.80/devops/webapp.git
        dest: /opt/webapp
        version: main

    - name: Install dependencies
      pip:
        requirements: /opt/webapp/requirements.txt

    - name: Restart service
      systemd:
        name: webapp
        state: restarted
`)
	w.files["/home/ansible/playbooks/deploy.yml"].Owner = "ansible"

	w.files["/home/ansible/playbooks/db_backup.yml"] = NewFileEntry(`---
- name: Database backup
  hosts: fin-db01
  become: yes
  vars:
    db_host: 192.168.56.60
    db_user: web_ro
    db_password: WebApp@2024!Ro
    backup_dir: /backups
  tasks:
    - name: Dump database
      command: mysqldump -h {{ db_host }} -u {{ db_user }} -p'{{ db_password }}' fin_readonly_` + DeploySeed + `
      register: dump_result

    - name: Save to file
      copy:
        content: "{{ dump_result.stdout }}"
        dest: "{{ backup_dir }}/db_{{ ansible_date_time.date }}.sql"
`)
	w.files["/home/ansible/playbooks/db_backup.yml"].Owner = "ansible"

	// === /var/log ===
	w.files["/var/log/auth.log"] = NewFileEntry(`Jan 15 08:00:01 staging-web-01 sshd[412]: Accepted publickey for root from 192.168.56.1 port 52341 ssh2
Jan 15 08:00:05 staging-web-01 sshd[412]: pam_unix(sshd:session): session opened for user root by (uid=0)
Jan 15 08:15:22 staging-web-01 sshd[425]: Accepted password for ansible from 192.168.56.10 port 41233 ssh2
Jan 15 08:15:25 staging-web-01 sshd[425]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jan 15 08:30:01 staging-web-01 CRON[892]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan 15 09:00:12 staging-web-01 sshd[512]: Failed password for root from 192.168.56.100 port 33421 ssh2
Jan 15 09:00:15 staging-web-01 sshd[512]: Failed password for root from 192.168.56.100 port 33421 ssh2
Jan 15 09:00:18 staging-web-01 sshd[512]: Connection closed by 192.168.56.100 port 33421 [preauth]
`)

	w.files["/var/log/syslog"] = NewFileEntry(`Jan 15 08:00:01 staging-web-01 systemd[1]: Started Web Application Service.
Jan 15 08:00:02 staging-web-01 kernel: [    0.000000] Linux version 5.15.0-91-generic
Jan 15 08:12:33 staging-web-01 webapp[523]: Connected to MySQL at 192.168.56.60:3306
Jan 15 08:15:01 staging-web-01 kernel: [842312.123] Memory cgroup out of memory: Killed process 1234 (python3)
Jan 15 08:20:45 staging-web-01 webapp[523]: Health check passed
Jan 15 08:25:12 staging-web-01 webapp[523]: Connection timeout to gitlab-internal (192.168.56.80)
Jan 15 08:30:00 staging-web-01 CRON[892]: (root) CMD /opt/webapp/scripts/backup.sh
Jan 15 09:00:00 staging-web-01 systemd[1]: Starting Daily apt activities...
`)

	w.files["/var/log/nginx/access.log"] = NewFileEntry(`192.168.56.1 - - [15/Jan/2024:08:00:01 +0000] "GET /health HTTP/1.1" 200 15 "-" "curl/7.88.1"
192.168.56.50 - - [15/Jan/2024:08:10:22 +0000] "GET /api/data HTTP/1.1" 200 89 "-" "python-requests/2.31.0"
192.168.56.100 - - [15/Jan/2024:09:00:12 +0000] "GET / HTTP/1.1" 200 256 "-" "Mozilla/5.0"
192.168.56.100 - - [15/Jan/2024:09:00:15 +0000] "GET /admin HTTP/1.1" 404 169 "-" "Mozilla/5.0"
192.168.56.100 - - [15/Jan/2024:09:00:18 +0000] "POST /login HTTP/1.1" 401 128 "-" "python-requests/2.31.0"
`)

	w.files["/var/log/nginx/error.log"] = NewFileEntry(`2024/01/15 08:25:12 [error] 345#345: *1234 connect() failed (110: Connection timed out) while connecting to upstream, client: 192.168.56.50, server: staging-web-01.corp.local
`)

	// === /var/www ===
	w.files["/var/www/html/index.html"] = NewFileEntry(`<!DOCTYPE html>
<html><head><title>Default</title></head>
<body><h1>nginx default page</h1></body>
</html>
`)

	// === /proc ===
	w.files["/proc/net/arp"] = NewFileEntry(`IP address       HW type     Flags       HW address            Mask     Device
192.168.56.1     0x1         0x2         00:50:56:xx:xx:01     *        eth0
192.168.56.50    0x1         0x2         00:50:56:xx:xx:02     *        eth0
192.168.56.60    0x1         0x2         00:50:56:xx:xx:03     *        eth0
192.168.56.80    0x1         0x2         00:50:56:xx:xx:04     *        eth0
192.168.56.30    0x1         0x2         00:50:56:xx:xx:05     *        eth0
`)

	w.files["/proc/version"] = NewFileEntry(`Linux version 5.15.0-91-generic (buildd@lcy02-amd64-045) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023
`)

	// === /tmp files ===
	w.files["/tmp/.env.bak"] = NewFileEntry(`DB_HOST=192.168.56.60
DB_PASSWORD=WebApp@2024!Ro
`)
	w.files["/tmp/.env.bak"].Permissions = "-rw-rw-rw-"

	// === /var/tmp ===
	w.files["/var/tmp/deploy.log"] = NewFileEntry(`2024-01-14 22:30:00 Deploy started by jenkins
2024-01-14 22:30:15 Pulling from gitlab-internal (192.168.56.80)
2024-01-14 22:31:00 Build completed
2024-01-14 22:31:30 Restarting webapp service
2024-01-14 22:32:00 Deploy completed successfully
`)

	// === tool binaries / realistic operator tooling ===
	for _, fp := range []string{
		"/usr/bin/python3", "/usr/bin/mysql", "/usr/bin/psql", "/usr/bin/pg_dump", "/usr/bin/curl", "/usr/bin/wget", "/usr/bin/ssh", "/usr/bin/scp",
		"/usr/bin/ping", "/usr/bin/dig", "/usr/bin/ldapsearch", "/usr/bin/smbclient", "/usr/bin/nmap",
		"/usr/bin/gobuster", "/usr/bin/ffuf", "/usr/bin/sqlmap", "/usr/bin/msfconsole",
		"/usr/local/bin/fscan", "/usr/local/bin/dddd2", "/usr/local/bin/nuclei", "/usr/local/bin/sliver-client",
	} {
		w.files[fp] = NewFileEntry("ELF 64-bit LSB pie executable, x86-64, dynamically linked\n")
		w.files[fp].Permissions = "-rwxr-xr-x"
		w.files[fp].Size = 145632
	}

	w.files["/home/deploy/.bash_history"] = NewFileEntry(`ssh jump01
ssh -D 1080 jump01
nmap -sV 192.168.56.0/24
fscan -h 192.168.56.0/24 -np
mysql -h 192.168.56.60 -u web_ro -p
curl -I http://192.168.56.80/devops/webapp
kubectl --kubeconfig ~/.kube/prod-finance get pods -n prod-finance
`)
	w.files["/home/deploy/.bash_history"].Owner = "deploy"

	w.files["/home/deploy/.git-credentials"] = NewFileEntry(`http://deploy:glpat-` + DeploySeed + `-deploy-token@192.168.56.80
`)
	w.files["/home/deploy/.git-credentials"].Owner = "deploy"
	w.files["/home/deploy/.git-credentials"].Permissions = "-rw-------"

	w.files["/home/deploy/.kube/config"] = NewFileEntry(`apiVersion: v1
clusters:
- cluster:
    server: https://192.168.56.45:6443
  name: prod-finance
contexts:
- context:
    cluster: prod-finance
    namespace: prod-finance
    user: deploy-readonly
  name: prod-finance
current-context: prod-finance
users:
- name: deploy-readonly
  user:
    token: k8s-decoy-readonly-` + DeploySeed + `
`)
	w.files["/home/deploy/.kube/config"].Owner = "deploy"
	w.files["/home/deploy/.kube/config"].Permissions = "-rw-------"

	w.files["/var/backups/webapp_20240115.tar.gz"] = NewFileEntry("gzip compressed data, original size 234881024 bytes, contains opt/webapp and partial config snapshots\n")
	w.files["/var/backups/db_20240115.sql"] = NewFileEntry(`-- partial backup
CREATE DATABASE fin_readonly_` + DeploySeed + `;
-- credentials moved to Jenkins credential store: jenkins-` + DeploySeed + `-build-token
-- next hop noted by ops: jump01 -> finance segment
`)
}

// ReadFile returns file content or empty string if not found.
func (w *WorldState) ReadFile(filepath string) string {
	if f, ok := w.files[filepath]; ok {
		return f.Content
	}
	return ""
}

// FileExists checks if a file exists.
func (w *WorldState) FileExists(filepath string) bool {
	_, ok := w.files[filepath]
	return ok
}

// GetFileEntry returns the file entry or nil.
func (w *WorldState) GetFileEntry(filepath string) *FileEntry {
	return w.files[filepath]
}

// IsDir checks if a path is a directory.
func (w *WorldState) IsDir(filepath string) bool {
	if f, ok := w.files[filepath]; ok {
		return f.Permissions[0] == 'd'
	}
	return false
}

// ListFiles returns sorted filenames in a directory.
func (w *WorldState) ListFiles(dir string) []string {
	dir = path.Clean(dir)
	var names []string
	for fp := range w.files {
		parent := path.Dir(fp)
		if parent == dir && fp != dir {
			name := path.Base(fp)
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names
}

// GetDirectoryListing returns ls -la style entries.
func (w *WorldState) GetDirectoryListing(dir string) []map[string]string {
	dir = path.Clean(dir)
	var entries []map[string]string

	// Add subdirectories (both direct entries and implicit dirs from deeper paths)
	subdirs := make(map[string]bool)
	for fp := range w.files {
		if !strings.HasPrefix(fp, dir+"/") || fp == dir {
			continue
		}
		rel := strings.TrimPrefix(fp, dir+"/")
		if idx := strings.Index(rel, "/"); idx > 0 {
			subdirs[rel[:idx]] = true
		}
	}

	// Also add explicit directory entries
	for fp, f := range w.files {
		if path.Dir(fp) != dir || fp == dir {
			continue
		}
		if f.Permissions[0] == 'd' {
			subdirs[path.Base(fp)] = true
		}
	}

	now := time.Now().UTC().Format("2006-01-02 15:04")
	for name := range subdirs {
		entries = append(entries, map[string]string{
			"permissions": "drwxr-xr-x",
			"links":       "2",
			"owner":       "root",
			"group":       "root",
			"size":        "4096",
			"mtime":       now,
			"name":        name,
		})
	}

	// Add files
	for fp, f := range w.files {
		if path.Dir(fp) != dir || fp == dir {
			continue
		}
		if f.Permissions[0] == 'd' {
			continue // already added above
		}
		entries = append(entries, map[string]string{
			"permissions": f.Permissions,
			"links":       "1",
			"owner":       f.Owner,
			"group":       f.Group,
			"size":        fmt.Sprintf("%d", f.Size),
			"mtime":       f.Mtime,
			"name":        path.Base(fp),
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i]["name"] < entries[j]["name"]
	})
	return entries
}

// AddFile adds a file to the world.
func (w *WorldState) AddFile(filepath string, entry *FileEntry) {
	w.files[filepath] = entry
}

// RebaseCIDR rewrites seeded /24 clue data to the active primary topology CIDR.
func (w *WorldState) RebaseCIDR(oldCIDR, newCIDR string) {
	oldPrefix := cidr24Prefix(oldCIDR)
	newPrefix := cidr24Prefix(newCIDR)
	if oldPrefix == "" || newPrefix == "" || oldPrefix == newPrefix {
		return
	}
	for _, entry := range w.files {
		if entry == nil || entry.Content == "" {
			continue
		}
		entry.Content = strings.ReplaceAll(entry.Content, oldPrefix+".", newPrefix+".")
		entry.Size = len(entry.Content)
	}
}

func cidr24Prefix(cidr string) string {
	if !strings.HasSuffix(cidr, "/24") {
		return ""
	}
	base := strings.TrimSuffix(cidr, "/24")
	parts := strings.Split(base, ".")
	if len(parts) != 4 {
		return ""
	}
	return strings.Join(parts[:3], ".")
}

// AllFiles returns all file paths in the world.
func (w *WorldState) AllFiles() []string {
	paths := make([]string, 0, len(w.files))
	for fp := range w.files {
		paths = append(paths, fp)
	}
	sort.Strings(paths)
	return paths
}

// InjectLsOutput parses LLM-generated ls output and injects entries into the
// filesystem so that subsequent commands (find, ls -l, cat, grep) on the same
// directory return consistent results.
func (w *WorldState) InjectLsOutput(dir, output string) {
	dir = path.Clean(dir)
	// Ensure the directory itself exists
	if _, ok := w.files[dir]; !ok {
		w.files[dir] = NewDirEntry("root")
	}

	lines := strings.Split(strings.TrimSpace(output), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		// Try to parse ls -l format: "drwxr-xr-x 2 root root 4096 Jan 15 08:00 dirname"
		if entry := parseLsLongLine(line); entry != nil {
			name := path.Base(line)
			// Extract name from the last field
			fields := strings.Fields(line)
			if len(fields) >= 7 {
				name = fields[len(fields)-1]
			}
			fp := dir + "/" + name
			if _, exists := w.files[fp]; !exists {
				w.files[fp] = entry
			}
			continue
		}

		// Short format: just filenames, possibly space-separated
		names := strings.Fields(line)
		for _, name := range names {
			name = strings.TrimRight(name, "/") // remove trailing /
			if name == "" || name == "." || name == ".." {
				continue
			}
			fp := dir + "/" + name
			if _, exists := w.files[fp]; !exists {
				// Guess if it's a directory (common convention: dirs have no extension)
				if strings.HasSuffix(line, name+"/") || isLikelyDir(name) {
					w.files[fp] = NewDirEntry("root")
				} else {
					w.files[fp] = NewFileEntry("")
				}
			}
		}
	}
}

// InjectCatOutput stores LLM-generated cat output as file content.
func (w *WorldState) InjectCatOutput(filepath, content string) {
	filepath = path.Clean(filepath)
	if entry, ok := w.files[filepath]; ok {
		entry.Content = content
		entry.Size = len(content)
	} else {
		w.files[filepath] = NewFileEntry(content)
	}
}

// parseLsLongLine tries to parse an ls -l output line.
// Returns nil if the line doesn't match the expected format.
func parseLsLongLine(line string) *FileEntry {
	fields := strings.Fields(line)
	if len(fields) < 8 {
		return nil
	}
	// Check if first field looks like permissions (e.g., drwxr-xr-x, -rw-r--r--)
	perm := fields[0]
	if len(perm) < 9 {
		return nil
	}
	switch perm[0] {
	case 'd', '-', 'l', 'c', 'b', 'p', 's':
		// valid permission prefix
	default:
		return nil
	}
	// Validate permission characters
	for _, c := range perm[1:] {
		switch c {
		case 'r', 'w', 'x', 's', 't', 'S', 'T', '-':
			// ok
		default:
			return nil
		}
	}

	entry := &FileEntry{
		Permissions: perm,
		Owner:       fields[2],
		Group:       fields[3],
		Mtime:       strings.Join(fields[5:8], " "),
	}
	fmt.Sscanf(fields[4], "%d", &entry.Size)
	return entry
}

// isLikelyDir returns true if the name looks like a directory (no extension,
// or is a well-known directory name).
func isLikelyDir(name string) bool {
	knownDirs := map[string]bool{
		"bin": true, "boot": true, "dev": true, "etc": true, "home": true,
		"lib": true, "lib64": true, "media": true, "mnt": true, "opt": true,
		"proc": true, "root": true, "run": true, "sbin": true, "srv": true,
		"sys": true, "tmp": true, "usr": true, "var": true,
		"src": true, "include": true, "share": true, "local": true,
		"config": true, "cache": true, "log": true, "data": true,
		"binfmt": true, "bus": true, "class": true, "firmware": true,
		"kernel": true, "power": true, "block": true, "devices": true,
		"fs": true, "net": true, "module": true,
	}
	if knownDirs[name] {
		return true
	}
	// No extension is a weak heuristic for directories
	return !strings.Contains(name, ".")
}
